<?php

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */

declare(strict_types=1);

namespace classes\Media;

use Atlas\Table\Table;

/**
 * @method MediaRow|null fetchRow($primaryVal)
 * @method MediaRow[] fetchRows(array $primaryVals)
 * @method MediaTableSelect select(array $whereEquals = [])
 * @method MediaRow newRow(array $cols = [])
 * @method MediaRow newSelectedRow(array $cols)
 */
class MediaTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'medias';

    const COLUMNS = [
        'id' => array(
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => true,
            'primary' => true,
            'options' => NULL,
        ),
        'gamesId' => array(
            'name' => 'gamesId',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => false,
            'primary' => true,
            'options' => NULL,
        ),
        'mediaType' => array(
            'name' => 'mediaType',
            'type' => 'varchar',
            'size' => 100,
            'scale' => NULL,
            'notnull' => true,
            'default' => 'image/png',
            'autoinc' => false,
            'primary' => false,
            'options' => NULL,
        ),
    ];

    const COLUMN_NAMES = [
        'id',
        'gamesId',
        'mediaType',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'gamesId' => null,
        'mediaType' => 'image/png',
    ];

    const PRIMARY_KEY = [
        'id',
        'gamesId',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
