<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Media;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 * @property mixed $mediaType varchar(100) NOT NULL
 */
class MediaRow extends Row
{
    protected $cols = [
        'id' => null,
        'gamesId' => null,
        'mediaType' => 'image/png',
    ];
}
