<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Media;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 * @property mixed $mediaType varchar(100) NOT NULL
 */
trait MediaFields
{
}
