@startuml Use Case Diagram
left to right direction
rectangle Api {
 rectangle Sessions { 
  usecase (Registrarse)
  usecase (Iniciar\nsesión)
  usecase (Cerrar\nsesión)
 }

 rectangle Management {
  usecase (Agregar\Editar\n Juego)
  usecase (Agregar\Editar\n Categoria)
  usecase (Agregar\Editar\n Plataforma)
 }

 usecase (Reportar\nincidencia)
 usecase (Realizar\ncomentario)
}

:User: --> (Registrarse)
:User: --> (Iniciar\nsesión)
:User: --> (Reportar\nincidencia)

:LoggedUser: ----> (Reportar\nincidencia)
:LoggedUser: --> (Cerrar\nsesión)
:LoggedUser: --> (Realizar\ncomentario)

:AdminUser: --|> :LoggedUser:
:AdminUser: --> (Agregar\Editar\n Juego)
:AdminUser: --> (Agregar\Editar\n Categoria)
:AdminUser: --> (Agregar\Editar\n Plataforma)
@enduml