<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\CategoriesGame;

use Atlas\Table\Row;

/**
 * @property mixed $categoriesId int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 */
class CategoriesGameRow extends Row
{
    protected $cols = [
        'categoriesId' => null,
        'gamesId' => null,
    ];
}
