<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Game;

use Atlas\Table\Table;

/**
 * @method GameRow|null fetchRow($primaryVal)
 * @method GameRow[] fetchRows(array $primaryVals)
 * @method GameTableSelect select(array $whereEquals = [])
 * @method GameRow newRow(array $cols = [])
 * @method GameRow newSelectedRow(array $cols)
 */
class GameTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'games';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'name' => array (
  'name' => 'name',
  'type' => 'varchar',
  'size' => 100,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'descripcion' => array (
  'name' => 'descripcion',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'descripcion',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'descripcion' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
