<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\PlataformsGame;

use Atlas\Table\Row;

/**
 * @property mixed $plataformsId int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 */
class PlataformsGameRow extends Row
{
    protected $cols = [
        'plataformsId' => null,
        'gamesId' => null,
    ];
}
