<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\PlataformsGame;

use Atlas\Table\Table;

/**
 * @method PlataformsGameRow|null fetchRow($primaryVal)
 * @method PlataformsGameRow[] fetchRows(array $primaryVals)
 * @method PlataformsGameTableSelect select(array $whereEquals = [])
 * @method PlataformsGameRow newRow(array $cols = [])
 * @method PlataformsGameRow newSelectedRow(array $cols)
 */
class PlataformsGameTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'plataforms_games';

    const COLUMNS = [
        'plataformsId' => array (
  'name' => 'plataformsId',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'gamesId' => array (
  'name' => 'gamesId',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'price' => array (
  'name' => 'price',
  'type' => 'float',
  'size' => 100,
  'scale' => 2,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'priceUnit' => array (
  'name' => 'priceUnit',
  'type' => 'varchar',
  'size' => 100,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'discount' => array (
  'name' => 'discount',
  'type' => 'float',
  'size' => 3,
  'scale' => 2,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'isEnabled' => array (
  'name' => 'isEnabled',
  'type' => 'tinyint',
  'size' => 3,
  'scale' => 0,
  'notnull' => true,
  'default' => 1,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'plataformsId',
        'gamesId',
        'price',
        'priceUnit',
        'discount',
        'isEnabled',
    ];

    const COLUMN_DEFAULTS = [
        'plataformsId' => null,
        'gamesId' => null,
        'price' => null,
        'priceUnit' => null,
        'discount' => null,
        'isEnabled' => 1,
    ];

    const PRIMARY_KEY = [
        'plataformsId',
        'gamesId',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
