<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\PlataformsGame;

/**
 * @property mixed $plataformsId int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 */
trait PlataformsGameFields
{
}
