<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\PlataformsGame;

use Atlas\Table\Row;

/**
 * @property mixed $plataformsId int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 * @property mixed $price float(100,2) NOT NULL
 * @property mixed $priceUnit varchar(100) NOT NULL
 * @property mixed $discount float(3,2) NOT NULL
 * @property mixed $isEnabled tinyint(3,0) NOT NULL
 */
class PlataformsGameRow extends Row
{
    protected $cols = [
        'plataformsId' => null,
        'gamesId' => null,
        'price' => null,
        'priceUnit' => null,
        'discount' => null,
        'isEnabled' => 1,
    ];
}
