<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Comment;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $usersId int(10,0) NOT NULL
 * @property mixed $gamesId int(10,0) NOT NULL
 * @property mixed $description varchar(255) NOT NULL
 */
class CommentRow extends Row
{
    protected $cols = [
        'id' => null,
        'usersId' => null,
        'gamesId' => null,
        'description' => null,
    ];
}
