<?php

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */

declare(strict_types=1);

namespace classes\Comment;

use Atlas\Table\Table;

/**
 * @method CommentRow|null fetchRow($primaryVal)
 * @method CommentRow[] fetchRows(array $primaryVals)
 * @method CommentTableSelect select(array $whereEquals = [])
 * @method CommentRow newRow(array $cols = [])
 * @method CommentRow newSelectedRow(array $cols)
 */
class CommentTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'comments';

    const COLUMNS = [
        'id' => array(
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => true,
            'primary' => true,
            'options' => NULL,
        ),
        'usersId' => array(
            'name' => 'usersId',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => false,
            'primary' => false,
            'options' => NULL,
        ),
        'gamesId' => array(
            'name' => 'gamesId',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => false,
            'primary' => false,
            'options' => NULL,
        ),
        'description' => array(
            'name' => 'description',
            'type' => 'varchar',
            'size' => 255,
            'scale' => NULL,
            'notnull' => true,
            'default' => NULL,
            'autoinc' => false,
            'primary' => false,
            'options' => NULL,
        ),
    ];

    const COLUMN_NAMES = [
        'id',
        'usersId',
        'gamesId',
        'description',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'usersId' => null,
        'gamesId' => null,
        'description' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
