<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\User;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $name varchar(100) NOT NULL
 * @property mixed $password varchar(255) NOT NULL
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $imageUrl varchar(255)
 * @property mixed $publicityAccepted tinyint(3,0)
 */
trait UserFields
{
}
