<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Plataform;

use Atlas\Table\Table;

/**
 * @method PlataformRow|null fetchRow($primaryVal)
 * @method PlataformRow[] fetchRows(array $primaryVals)
 * @method PlataformTableSelect select(array $whereEquals = [])
 * @method PlataformRow newRow(array $cols = [])
 * @method PlataformRow newSelectedRow(array $cols)
 */
class PlataformTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'plataforms';

    const COLUMNS = [
        'id' => array (
  'name' => 'id',
  'type' => 'int',
  'size' => 10,
  'scale' => 0,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'name' => array (
  'name' => 'name',
  'type' => 'varchar',
  'size' => 100,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'url' => array (
  'name' => 'url',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'url',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'url' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
