<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Category;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $name varchar(100) NOT NULL
 */
trait CategoryFields
{
}
