<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace classes\Category;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL AUTO_INCREMENT
 * @property mixed $name varchar(100) NOT NULL
 */
class CategoryRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
    ];
}
