const DESTINATION_GAMES = '/game';
const DESTINATION_PLATAFORM_GAMES = '/games';
const DESTINATION_LIST_OF_GAMES = '/games/listed';

const DESTINATION_CATEGORY = '/category';
const DESTINATION_CATEGORIES = '/categories';
const DESTINATION_CATEGORIES_UPDATES = '/categories/update';

const DESTINATION_PLATAFORM = '/plataform';
const DESTINATION_PLATAFORMS = '/plataforms';
const DESTINATION_PLATAFORMS_UPDATES = '/plataforms/update';

const DESTINATION_COMMENT = '/comment';
const DESTINATION_LOGIN = '/logIn';
const DESTINATION_SIGNIN = '/signIn';
const DESTINATION_REPORT = '/report';

export {
    DESTINATION_GAMES,
    DESTINATION_LIST_OF_GAMES,
    DESTINATION_PLATAFORM_GAMES, 

    DESTINATION_CATEGORY,
    DESTINATION_CATEGORIES, 
    DESTINATION_CATEGORIES_UPDATES,

    DESTINATION_PLATAFORM,
    DESTINATION_PLATAFORMS,
    DESTINATION_PLATAFORMS_UPDATES,

    DESTINATION_COMMENT,
    DESTINATION_LOGIN,
    DESTINATION_SIGNIN,
    DESTINATION_REPORT
};

export const ALL_DESTINATIONS = [
    DESTINATION_GAMES, 
    DESTINATION_LIST_OF_GAMES,
    DESTINATION_PLATAFORM_GAMES, 

    DESTINATION_CATEGORY,
    DESTINATION_CATEGORIES, 
    DESTINATION_CATEGORIES_UPDATES,

    DESTINATION_PLATAFORM,
    DESTINATION_PLATAFORMS,
    DESTINATION_PLATAFORMS_UPDATES,

    DESTINATION_COMMENT,
    DESTINATION_LOGIN,
    DESTINATION_SIGNIN,
    DESTINATION_REPORT
];
