const DESTINATION_GAMES = '/games';
const DESTINATION_PLATAFORM_GAMES = '/plataformGames';
const DESTINATION_CATEGORIES = '/categories';
const DESTINATION_PLATAFORMS = '/plataforms';

const DESTINATION_COMMENT = '/comment';
const DESTINATION_LOGIN = '/logIn';
const DESTINATION_SIGNIN = '/signIn';

export {
    DESTINATION_GAMES, 
    DESTINATION_PLATAFORM_GAMES, 
    DESTINATION_CATEGORIES, 
    DESTINATION_PLATAFORMS,

    DESTINATION_COMMENT,
    DESTINATION_LOGIN,
    DESTINATION_SIGNIN
};

export const ALL_DESTINATIONS = [
    DESTINATION_GAMES, 
    DESTINATION_PLATAFORM_GAMES, 
    DESTINATION_CATEGORIES, 
    DESTINATION_PLATAFORMS,

    DESTINATION_COMMENT,
    DESTINATION_LOGIN,
    DESTINATION_SIGNIN
];